### ISSUE TITLE
File google-services.json is missing

### ISSUE THREAD

**Issue by csguzman** [actions-on-google/appactions-fitness-kotlin#1]
org.gradle.api.GradleException: File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by dzuluaga** [comment]
Can you try creating your own?
https://firebase.google.com/docs/android/setup#add-config-file

**Comment by Polar-Points** [comment]
Linking the downloaded sample to firebase via the firebase connection assistant should remove the error

**Comment by skimarxall** [comment]
We just published a new version, that includes a gradle tasks to quickly rename the package name.

Please check [Quick Setup](https://github.com/actions-on-google/appactions-fitness-kotlin#quick-setup)
