### ISSUE TITLE
Examples not working - inconsistency

### ISSUE THREAD

**Issue by ArseneR81** [actions-on-google/appactions-fitness-kotlin#26]
I am trying this Google Assistant example here, quite for a while - in vain. There are different ways described, but none of them work properly. 

1. [Here it is described](https://github.com/actions-on-google/appactions-fitness-kotlin#requirements) to generate a google-services.json and to put that into the app/ folder. I tried that twice as described, I was logged in with that very same Google Account on Android Studio, on my physical device and its Google Assistant account, etc.
2. [Here we have a step by step tutorial](https://codelabs.developers.google.com/codelabs/appactions#0) by Google Codelabs and I tried everything until [step 4](https://codelabs.developers.google.com/codelabs/appactions#4), where I install the Action Test plugin. However, clicking the run in that plugin opens a google Assistant in my device telling me "Sorry I could not find anything" regarding that voice command. Also until step 4, I couldnt find anything regarding a google-services.json? Instead I had to upload an internal test release version into my Playstore, which in turn was not mentioned in 1.

**Comment by ArseneR81** [comment]
This adb command `adb shell am start -a android.intent.action.VIEW -d "https://fit-actions.firebaseapp.com/start"`
is working so far. 

As I said, the App Action test plugin will not start the app..

**Comment by dzuluaga** [comment]
Thanks for reaching out. Two recommendations for getting started with App Actions:

1. Try the [codelabs](https://developers.google.com/assistant/app/codelabs) first. These codelabs are based on this app, so you'll be able to build the same app from scratch.
2. Use [this checklist](https://developers.google.com/assistant/app/troubleshoot#test_5) for troubleshooting the error `Sorry, I couldn't find that`.

**Comment by ArseneR81** [comment]
> Thanks for reaching out. Two recommendations for getting started with App Actions:
> 2. Use [this checklist](https://developers.google.com/assistant/app/troubleshoot#test_5) for troubleshooting the error `Sorry, I couldn't find that`.

Thank you. 3. The Google Assistant device language was german on my phone :) That solved it!
