### ISSUE TITLE
Where to change BII?

### ISSUE THREAD

**Issue by ArseneR81** [actions-on-google/appactions-fitness-kotlin#28]
Instead of calling 

> ok google, start running in fit actions

I would like to change/add own commands like

> ok google, start recording in fit actions

or just

> ok google, play in fit actions

**Comment by CodingDoug** [comment]
Each BII has been tuned to recognize specific language patterns.  It's not possible to change those patterns.  You can see examples of the speech recognized for START_EXERCISE in the documentation:

https://developers.google.com/assistant/app/reference/built-in-intents/health-and-fitness/start-exercise

If you want to choose a new BII, you can use the documentation to try to find one that matches your use case.  Or you can create a custom intent with the patterns you want.
