### ISSUE TITLE
App-action test tool isn't working

### ISSUE THREAD

**Issue by danagibson** [actions-on-google/appactions-fitness-kotlin#29]
Opens a window but in bottom right corner points out an error in invoking it...okhtt3.OkHttpClient$Builder class not found.

**Comment by CodingDoug** [comment]
Hello.  If you have a bug report for the test tool, please use the bug tracker dedicated for that.

https://issuetracker.google.com/issues/new?component=617864

Your bug report should contain enough information that anyone can use to reproduce the issue, including the complete set of steps to take, and the versions of all the software you're using (Android Studio, the plugin itself).

**Comment by danagibson** [comment]
I got this working by going backwards until I found a version that still didn't work but when I did the update it was done by a third party and they did it correctly to make it work. Really get tired of the "you're entering this in the wrong place, find someone who cares" mentality.
