### ISSUE TITLE
Running sample via voice

### ISSUE THREAD

**Issue by Polar-Points** [actions-on-google/appactions-fitness-kotlin#3]
Hey!

I have clone this sample onto my local machine. I connected the sample to firebase to get rid of the missing google-services.json. I then open up google assistant and say " Start my run using Fitness Action Sample” but the app doesn't start, instead I get a google search page. Do I need to upload this apk as a draft for me to be able to trigger via voice?

Thanks!

**Comment by dzuluaga** [comment]
Correct. Duplicate #2
