### ISSUE TITLE
Not able to open the app through google assistant 

### ISSUE THREAD

**Issue by sushanthNiveus** [actions-on-google/appactions-fitness-kotlin#6]
I have setup the project, uploaded the draft in play console, tried running action using app actions test tool. But Google assistant returns saying 'Sorry. Couldn't find that'. I have tried with the deep linking that is was already there in the project and also, i tried with custom scheme for deep linking. I am able to start the app using custom URI scheme from cmd. Account used in mobile device, play console and android studio are all same. 
Also, please tell me how to change google account in app actions tool. I tried uninstalling and installing again but it directly takes to tool without asking me to login again. 
<img width="960" alt="Capture1" src="https://user-images.githubusercontent.com/13234541/58399398-b48a4400-8075-11e9-9411-1b94e5c2a000.PNG">
![2019-05-25](https://user-images.githubusercontent.com/13234541/58399440-d08de580-8075-11e9-9d74-e7359300e896.png)

**Comment by adamkoch** [comment]
For general troubleshooting steps that aren't related to code for this sample app, please post on stackoverflow instead using the app-actions tag: https://stackoverflow.com/questions/tagged/app-actions - thanks!

Make sure you have updated your [Google app](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=en) to the latest version and see if that helps.

> Also, please tell me how to change google account in app actions tool. I tried uninstalling and installing again but it directly takes to tool without asking me to login again.

It uses the Android Studio login credentials, you can logout by clicking the little profile icon in the top right corner of Android Studio.

<img width="232" alt="Screen Shot 2019-05-27 at 3 21 13 PM" src="https://user-images.githubusercontent.com/869261/58443482-705e7880-8135-11e9-9ca4-c0ba89bbf440.png">

**Comment by parampreets** [comment]
same issue, not working for me too.

**Comment by harshfast** [comment]
@skimarxall @parampreets @adamkoch 
Same issue I am also facing if anyone has fixed please reply to the same thread.
Steps:
- Uploaded the APK to play store internal test track in draft mode
- Logged in with same account to **(Device, PlayConsole and Android Studio)**
- Changed the packageId to the app which I have uploaded to playstore
- Running App Actions Test Tool -> **Preview uploaded successfully**
- **Run** -> Opens Assistant in device with message **'Sorry, Couldn't find that'**

Let me know if I have missed any step. Thank you

**Comment by adamkoch** [comment]
I put some more troubleshooting steps in your SO post:
https://stackoverflow.com/a/57951935/268156

Please try and let me know on SO how you go.
