### ISSUE TITLE
Not able to install Google Assistant

### ISSUE THREAD

**Issue by vdaele** [actions-on-google/appactions-fitness-kotlin#7]
One requirement to run this example application is to install https://play.google.com/store/apps/details?id=com.google.android.apps.googleassistant&hl=en
However, I can't seem to install this on my (rooted) Galaxy S3 running Android 7.1.2  Any ideas?

And one more clarification: with this example, I will be able to talk to the Google Assistant on my phone and it will start this app, right?  
Will I also be able to talk to the Google Assistant inside my Google Home (mini) to start the app on my phone?

**Comment by adamkoch** [comment]
For general troubleshooting steps and tech questions that aren't related to code for this sample app, please post on stackoverflow instead using the app-actions tag: https://stackoverflow.com/questions/tagged/app-actions - thanks!

I'm not sure about the Google Assistant issue, sorry. But as long as you can install the latest version of the [Google app](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=en) and also start and use the Google Assistant on your phone, then App Actions should work.

> And one more clarification: with this example, I will be able to talk to the Google Assistant on my phone and it will start this app, right?

Yes, correct.

> Will I also be able to talk to the Google Assistant inside my Google Home (mini) to start the app on my phone?

No, this will not work. App Actions is only for calling upon an Android app from Assistant on an Android device. To create voice "apps" for Google Home and non-Android Assistant surfaces you should use one of the other Actions on Google APIs here:
https://developers.google.com/actions/assistant/
